import type { Metadata } from "next"
import Header from "@/components/Header"
import "../globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { SanityLive } from "@/sanity/lib/live"


export const metadata: Metadata = {
  title: "Shopr App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          <main>
            <Header />
            {children}
          </main>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
    
  )
}
